# Generated by Django 3.0.5 on 2020-04-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200413_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='comment',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.IntegerField(choices=[(0, 'Costs'), (1, 'Income')]),
        ),
    ]
