# Generated by Django 3.0.5 on 2020-04-14 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200413_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
